name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          xbps-install -Syu xbps
          xbps-install -Sy xtools-minimal dosfstools e2fsprogs util-linux openssl
      - name: Build
        run: ./build_img.sh
      - uses: actions/upload-artifact@v4
        with:
          name: avoid-img
          path: avoid.img

  package-gz:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: avoid-img
          path: .
      - name: Compress
        run: ./build_img_gz.sh
      - uses: actions/upload-artifact@v4
        with:
          name: avoid-img-gz
          path: avoid.img.gz

  package-qcow2:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: avoid-img
          path: .
      - name: Install dependencies
        run: |
          xbps-install -Syu xbps
          xbps-install -Sy qemu-img e2fsprogs util-linux
      - name: Convert to qcow2
        run: ./build_qcow2.sh
      - uses: actions/upload-artifact@v4
        with:
          name: avoid-qcow2
          path: avoid.qcow2

  release:
    needs: [package-gz, package-qcow2]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --privileged -v /dev:/dev
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: avoid-img-gz
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: avoid-qcow2
          path: .
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            avoid.img.gz
            avoid.qcow2
